
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hwfjpqcdiottcqyxqhyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3ZmpwcWNkaW90dGNxeXhxaHlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTAxNjAsImV4cCI6MjA2NTU4NjE2MH0.syZ5H0GrWicLPSno6tXhkpLc-tYoQMrYNqIl98BVX94";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});
