// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpopbcevzngljgygmelc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwb3BiY2V2em5nbGpneWdtZWxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNjk0ODEsImV4cCI6MjA2NTk0NTQ4MX0.3N6FSvN32Vc2zXPFz33X0_e8hordCrMC-j5tzHORLGY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);